Run `cake upgrade` on the tests and code, update base files
This upgrades the unit test files to phpunit 8 and makes all of the
recommended changes for the rest of the code for Cake 4.0-4.5. It also
updates some files that didn't have a lot of custom changes to closely
match the files in the CakePHP app skeleton.

diff --git a/bropkg/bin/cake b/bropkg/bin/cake
--- a/bropkg/bin/cake
+++ b/bropkg/bin/cake
@@ -1,6 +1,5 @@
 #!/usr/bin/env sh
 # shellcheck disable=all
-
 ################################################################################
 #
 # Cake is a shell script for invoking CakePHP shell commands
@@ -29,18 +28,43 @@ canonicalize() {
     while [ -h "$NAME" ]; do
         DIR=$(dirname -- "$NAME")
         SYM=$(readlink "$NAME")
-        NAME=$(cd "$DIR" >/dev/null && cd $(dirname -- "$SYM") >/dev/null && pwd)/$(basename -- "$SYM")
+        NAME=$(cd "$DIR" >/dev/null && cd "$(dirname -- "$SYM")" >/dev/null && pwd)/$(basename -- "$SYM")
     done
     echo "$NAME"
 }
 
-CONSOLE=$(dirname -- "$(canonicalize "$0")")
+# Find a CLI version of PHP
+findCliPhp() {
+    for TESTEXEC in php php-cli /usr/local/bin/php; do
+        SAPI=$(echo "<?= PHP_SAPI ?>" | $TESTEXEC 2>/dev/null)
+        if [ "$SAPI" = "cli" ]; then
+            echo $TESTEXEC
+            return
+        fi
+    done
+    echo "Failed to find a CLI version of PHP; falling back to system standard php executable" >&2
+    echo "php"
+}
+
+# If current path is a symlink, resolve to real path
+realname="$0"
+if [ -L "$realname" ]; then
+    realname=$(readlink -f "$0")
+fi
+
+CONSOLE=$(dirname -- "$(canonicalize "$realname")")
 APP=$(dirname "$CONSOLE")
 
-if [ $(basename $0) != 'cake' ]; then
-    exec php "$CONSOLE"/cake.php $(basename $0) "$@"
+# If your CLI PHP is somewhere that this doesn't find, you can define a PHP environment
+# variable with the correct path in it.
+if [ -z "$PHP" ]; then
+    PHP=$(findCliPhp)
+fi
+
+if [ "$(basename "$realname")" != 'cake' ]; then
+    exec "$PHP" "$CONSOLE"/cake.php "$(basename "$realname")" "$@"
 else
-    exec php "$CONSOLE"/cake.php "$@"
+    exec "$PHP" "$CONSOLE"/cake.php "$@"
 fi
 
 exit
